from datetime import datetime
import oracledb
import os
from dotenv import load_dotenv
from typing import Optional

# Carga las variables de entorno desde el archivo .env
load_dotenv()


ORACLE_USER = "C##christopher_ruiz"
ORACLE_PASSWORD = "Inacap#2025"
ORACLE_DSN = "10.50.1.0/xe"


# Configuración de la conexión a Oracle
username = os.getenv("ORACLE_USER")
dsn = os.getenv("ORACLE_DSN")
password = os.getenv("ORACLE_PASSWORD")


def clear_screen():
    """Limpia la pantalla de la consola para mejor UX."""
    os.system("cls" if os.name == "nt" else "clear")


def get_connection():
    """Establece y retorna una conexión a la base de datos Oracle."""
    # Se asume que las variables de entorno están cargadas correctamente
    try:
        return oracledb.connect(user=username, password=password, dsn=dsn)
    except oracledb.DatabaseError as error:
        print(f"Error de conexión a la base de datos: {error}")
        return None


# --- Funciones de Esquema (Creación de Tablas) ---

def create_schema(query: str):
    """Ejecuta una consulta DDL para crear una tabla."""
    try:
        with get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(query)
                print(f"Tabla creada exitosamente:\n{query}")
    except oracledb.DatabaseError as error:
        # Se ignora el error si la tabla ya existe (ORA-00955)
        if "ORA-00955" in str(error):
            print(f"La tabla ya existe (no se pudo crear): {error.message.split(':', 1)[0]}")
        else:
            print(f"No se pudo crear la tabla: {error}")

def create_all_tables():
    """Define y crea todas las tablas de mascotas."""
    tables = [
        # Tabla Principal: MASCOTAS
        (
            "CREATE TABLE MASCOTAS ("
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," 
            "nombre VARCHAR(64) NOT NULL,"
            "especie VARCHAR(10) NOT NULL CHECK (especie IN ('GATO', 'PERRO', 'AVE')),"
            "fecha_nacimiento DATE,"
            "dueno VARCHAR(64)," 
            "fecha_registro DATE DEFAULT SYSDATE"
            ")"
        ),
        # Tabla Específica: PERRO
        (
            "CREATE TABLE PERRO ("
            "idMascota INTEGER PRIMARY KEY,"
            "raza VARCHAR(50),"
            "adiestramiento VARCHAR(50),"
            "FOREIGN KEY (idMascota) REFERENCES MASCOTAS(id) ON DELETE CASCADE"
            ")"
        ),
        # Tabla Específica: GATO
        (
            "CREATE TABLE GATO ("
            "idMascota INTEGER PRIMARY KEY,"
            "pelaje VARCHAR(50),"
            "es_cazador CHAR(1) CHECK (es_cazador IN ('S', 'N')),"
            "FOREIGN KEY (idMascota) REFERENCES MASCOTAS(id) ON DELETE CASCADE"
            ")"
        ),
        # Tabla Específica: AVE
        (
            "CREATE TABLE AVE ("
            "idMascota INTEGER PRIMARY KEY,"
            "tipo_pico VARCHAR(50),"
            "puede_volar CHAR(1) CHECK (puede_volar IN ('S', 'N')),"
            "FOREIGN KEY (idMascota) REFERENCES MASCOTAS(id) ON DELETE CASCADE"
            ")"
        ),
    ]

    for query in tables:
        create_schema(query)

# --- Funciones CRUD: MASCOTAS (Principal) ---

# CREATE
def create_mascota(
    nombre: str, especie: str, dueno: str, fecha_nacimiento: str
) -> Optional[int]:
    """Inserta una nueva mascota en la tabla MASCOTAS y retorna su ID."""
    sql = (
        "INSERT INTO MASCOTAS(nombre, especie, dueno, fecha_nacimiento)"
        "VALUES (:nombre, :especie, :dueno, :fecha_nacimiento) RETURNING id INTO :new_id"
    )
    
    new_id = oracledb.BIND() 

    parametros = {
        "nombre": nombre,
        "especie": especie.upper(),
        "dueno": dueno,
        # Convertir la fecha de string a objeto datetime
        "fecha_nacimiento": datetime.strptime(fecha_nacimiento, "%d-%m-%Y"),
        "new_id": new_id
    }

    try:
        connection = get_connection()
        if connection is None: return None
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                connection.commit()
                # Recuperar el ID generado
                mascota_id = parametros["new_id"].getvalue()[0]
                print(f"Mascota '{nombre}' insertada correctamente con ID: {mascota_id}")
                return mascota_id
    except oracledb.DatabaseError as error:
        print(f"No se pudo insertar la mascota:\n{error}\nSQL: {sql}\nParámetros: {parametros}")
        return None

# READ ALL
def read_mascotas():
    """Consulta y muestra todos los registros de la tabla MASCOTAS."""
    sql = "SELECT id, nombre, especie, dueno, fecha_nacimiento, fecha_registro FROM MASCOTAS ORDER BY id"
    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                print(f"Consulta: {sql}")
                resultados = cursor.execute(sql)
                # Encabezado de la tabla
                print("-" * 80)
                print(f"{'ID':<4} {'Nombre':<15} {'Especie':<10} {'Dueño':<15} {'F. Nacimiento':<15} {'F. Registro':<15}")
                print("-" * 80)
                
                found = False
                for fila in resultados:
                    found = True
                    # Formatear la fecha para mejor visualización
                    fecha_nac = fila[4].strftime("%d-%m-%Y") if fila[4] else "N/A"
                    fecha_reg = fila[5].strftime("%d-%m-%Y") if fila[5] else "N/A"
                    print(f"{fila[0]:<4} {fila[1]:<15} {fila[2]:<10} {fila[3]:<15} {fecha_nac:<15} {fecha_reg:<15}")
                
                if not found:
                    print("No se encontraron registros en la tabla MASCOTAS.")
                print("-" * 80)

    except oracledb.DatabaseError as error:
        print(f"No se pudo ejecutar la consulta:\n{error}\nSQL: {sql}")

# READ BY ID (Implementación Faltante)
def read_mascota_by_id(id_mascota: int):
    """Consulta y muestra una mascota por ID."""
    sql = "SELECT id, nombre, especie, dueno, fecha_nacimiento, fecha_registro FROM MASCOTAS WHERE id = :id_mascota"
    parametros = {"id_mascota": id_mascota}
    
    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                resultado = cursor.fetchone()
                
                if resultado:
                    print("-" * 80)
                    print("Detalle de Mascota:")
                    print("-" * 80)
                    fecha_nac = resultado[4].strftime("%d-%m-%Y") if resultado[4] else "N/A"
                    fecha_reg = resultado[5].strftime("%d-%m-%Y") if resultado[5] else "N/A"
                    
                    print(f"ID: {resultado[0]}")
                    print(f"Nombre: {resultado[1]}")
                    print(f"Especie: {resultado[2]}")
                    print(f"Dueño: {resultado[3]}")
                    print(f"Fecha Nacimiento: {fecha_nac}")
                    print(f"Fecha Registro: {fecha_reg}")
                    print("-" * 80)
                else:
                    print(f"No se encontró ninguna mascota con el ID: {id_mascota}")

    except oracledb.DatabaseError as error:
        print(f"No se pudo ejecutar la consulta:\n{error}\nSQL: {sql}\nParámetros: {parametros}")

# UPDATE (Implementación Faltante)
def update_mascota(
    id: int,
    nombre: Optional[str] = None,
    especie: Optional[str] = None,
    dueno: Optional[str] = None,
    fecha_nacimiento: Optional[str] = None,
):
    """Actualiza los datos de la mascota por ID."""
    modificaciones = []
    parametros = {"id": id}

    if nombre is not None:
        modificaciones.append("nombre = :nombre")
        parametros["nombre"] = nombre
    if especie is not None:
        modificaciones.append("especie = :especie")
        parametros["especie"] = especie.upper()
    if dueno is not None:
        modificaciones.append("dueno = :dueno")
        parametros["dueno"] = dueno
    if fecha_nacimiento is not None:
        modificaciones.append("fecha_nacimiento = :fecha_nacimiento")
        # Asegurarse de usar el formato de fecha correcto para la conversión
        try:
            parametros["fecha_nacimiento"] = datetime.strptime(fecha_nacimiento, "%d-%m-%Y")
        except ValueError:
            print("Error: Formato de fecha de nacimiento incorrecto. Use DD-MM-YYYY.")
            return
            
    if not modificaciones:
        return print("No has enviado datos por modificar.")

    sql = f"UPDATE MASCOTAS SET { ', '.join(modificaciones) } WHERE id = :id"

    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                if cursor.rowcount > 0:
                    connection.commit()
                    print(f"Dato de mascota con ID={id} actualizado correctamente.")
                else:
                    print(f"No se encontró la mascota con ID={id} para actualizar.")
    except oracledb.DatabaseError as error:
        print(f"Error al actualizar el dato:\n{error}\nSQL: {sql}\nParámetros: {parametros}")

# DELETE (Implementación Faltante)
def delete_mascota(id: int):
    """Elimina una mascota por ID (y sus detalles específicos debido a ON DELETE CASCADE)."""
    sql = "DELETE FROM MASCOTAS WHERE id = :id"
    parametros = {"id": id}

    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                if cursor.rowcount > 0:
                    connection.commit()
                    print(f"Mascota con ID={id} y sus detalles específicos han sido eliminados correctamente.")
                else:
                    print(f"No se encontró la mascota con ID={id} para eliminar.")
    except oracledb.DatabaseError as error:
        print(f"Error al eliminar la mascota:\n{error}\nSQL: {sql}\nParámetros: {parametros}")


# --- Funciones de Inserción de Detalles Específicos ---
# CREATE PERRO
def create_perro(idMascota: int, raza: str, adiestramiento: Optional[str] = None):
    """Inserta detalles específicos para un Perro, asumiendo que la mascota ya existe."""
    sql = (
        "INSERT INTO PERRO(idMascota, raza, adiestramiento)"
        "VALUES (:idMascota, :raza, :adiestramiento)"
    )
    parametros = {
        "idMascota": idMascota,
        "raza": raza,
        "adiestramiento": adiestramiento,
    }

    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
            connection.commit()
            print(f"Detalles de PERRO para ID Mascota {idMascota} insertados correctamente.")
    except oracledb.DatabaseError as error:
        print(f"No se pudo insertar el detalle de PERRO:\n{error}\nSQL: {sql}\nParámetros: {parametros}")

# CREATE GATO
def create_gato(idMascota: int, pelaje: str, es_cazador: str):
    """Inserta detalles específicos para un Gato, asumiendo que la mascota ya existe."""
    sql = (
        "INSERT INTO GATO(idMascota, pelaje, es_cazador)"
        "VALUES (:idMascota, :pelaje, :es_cazador)"
    )
    parametros = {
        "idMascota": idMascota,
        "pelaje": pelaje,
        "es_cazador": es_cazador.upper(),
    }

    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
            connection.commit()
            print(f"Detalles de GATO para ID Mascota {idMascota} insertados correctamente.")
    except oracledb.DatabaseError as error:
        print(f"No se pudo insertar el detalle de GATO:\n{error}\nSQL: {sql}\nParámetros: {parametros}")

# CREATE AVE
def create_ave(idMascota: int, tipo_pico: str, puede_volar: str):
    """Inserta detalles específicos para un Ave, asumiendo que la mascota ya existe."""
    sql = (
        "INSERT INTO AVE(idMascota, tipo_pico, puede_volar)"
        "VALUES (:idMascota, :tipo_pico, :puede_volar)"
    )
    parametros = {
        "idMascota": idMascota,
        "tipo_pico": tipo_pico,
        "puede_volar": puede_volar.upper(),
    }

    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
            connection.commit()
            print(f"Detalles de AVE para ID Mascota {idMascota} insertados correctamente.")
    except oracledb.DatabaseError as error:
        print(f"No se pudo insertar el detalle de AVE:\n{error}\nSQL: {sql}\nParámetros: {parametros}")


# --- Funciones de Lectura de Detalles Específicos (Nuevas) ---

def read_perro_by_id(id_mascota: int):
    """Consulta y muestra los detalles de PERRO por idMascota."""
    sql = "SELECT idMascota, raza, adiestramiento FROM PERRO WHERE idMascota = :id"
    parametros = {"id": id_mascota}
    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                resultado = cursor.fetchone()
                if resultado:
                    print("\n--- Detalles Específicos de PERRO ---")
                    print(f"ID Mascota: {resultado[0]}, Raza: {resultado[1]}, Adiestramiento: {resultado[2]}")
                else:
                    print(f"No hay detalles de PERRO para el ID Mascota: {id_mascota}")
    except oracledb.DatabaseError as error:
        print(f"Error al consultar detalles de PERRO:\n{error}")

def read_gato_by_id(id_mascota: int):
    """Consulta y muestra los detalles de GATO por idMascota."""
    sql = "SELECT idMascota, pelaje, es_cazador FROM GATO WHERE idMascota = :id"
    parametros = {"id": id_mascota}
    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                resultado = cursor.fetchone()
                if resultado:
                    print("\n--- Detalles Específicos de GATO ---")
                    es_cazador_str = "Sí" if resultado[2] == 'S' else "No"
                    print(f"ID Mascota: {resultado[0]}, Pelaje: {resultado[1]}, ¿Es Cazador?: {es_cazador_str}")
                else:
                    print(f"No hay detalles de GATO para el ID Mascota: {id_mascota}")
    except oracledb.DatabaseError as error:
        print(f"Error al consultar detalles de GATO:\n{error}")

def read_ave_by_id(id_mascota: int):
    """Consulta y muestra los detalles de AVE por idMascota."""
    sql = "SELECT idMascota, tipo_pico, puede_volar FROM AVE WHERE idMascota = :id"
    parametros = {"id": id_mascota}
    try:
        connection = get_connection()
        if connection is None: return
        with connection:
            with connection.cursor() as cursor:
                cursor.execute(sql, parametros)
                resultado = cursor.fetchone()
                if resultado:
                    print("\n--- Detalles Específicos de AVE ---")
                    puede_volar_str = "Sí" if resultado[2] == 'S' else "No"
                    print(f"ID Mascota: {resultado[0]}, Tipo de Pico: {resultado[1]}, ¿Puede Volar?: {puede_volar_str}")
                else:
                    print(f"No hay detalles de AVE para el ID Mascota: {id_mascota}")
    except oracledb.DatabaseError as error:
        print(f"Error al consultar detalles de AVE:\n{error}")


# --- Funciones de Menú (Adaptadas) ---

def menu_mascotas():
    """Menú CRUD para la tabla principal MASCOTAS y sus detalles."""
    while True:
        clear_screen()
        print(
            """
                ====================================
                |         Menu: Mascotas           |
                |----------------------------------|
                | 1. Insertar nueva mascota        |
                | 2. Consultar todas las mascotas  |
                | 3. Consultar mascota por ID      |
                | 4. Modificar mascota             |
                | 5. Eliminar mascota              |
                | 6. Consultar detalles específicos|
                | 0. Volver al menu principal      |
                ====================================
            """
        )
        opcion = input("Elige una opción [1-6, 0]: ")
        
        if opcion == "1":
            clear_screen()
            print("1. Insertar nueva mascota")
            nombre = input("Ingrese nombre de la mascota: ")
            
            while True:
                especie = input("Ingrese especie (GATO, PERRO, AVE): ").upper()
                if especie in ['GATO', 'PERRO', 'AVE']:
                    break
                print("Especie no válida. Intente de nuevo.")

            dueno = input("Ingrese nombre del dueño: ")
            fecha_nacimiento = input("Ingrese fecha de nacimiento (DD-MM-YYYY): ")
            
            mascota_id = create_mascota(nombre, especie, dueno, fecha_nacimiento)

            if mascota_id:
                print("\n--- Ingrese detalles específicos ---")
                if especie == "PERRO":
                    raza = input("Ingrese raza del perro: ")
                    adiestramiento = input("Ingrese tipo de adiestramiento (opcional): ")
                    create_perro(mascota_id, raza, adiestramiento if adiestramiento.strip() else None)
                elif especie == "GATO":
                    pelaje = input("Ingrese tipo de pelaje (CORTO/LARGO): ")
                    es_cazador = input("¿Es cazador? (S/N): ")
                    create_gato(mascota_id, pelaje, es_cazador)
                elif especie == "AVE":
                    tipo_pico = input("Ingrese tipo de pico: ")
                    puede_volar = input("¿Puede volar? (S/N): ")
                    create_ave(mascota_id, tipo_pico, puede_volar)
            
            input("\nPresione ENTER para continuar...")

        elif opcion == "2":
            clear_screen()
            print("2. Consultar todas las mascotas")
            read_mascotas()
            input("\nPresione ENTER para continuar...")
        
        elif opcion == "3":
            clear_screen()
            print("3. Consultar mascota por ID")
            try:
                id_mascota = int(input("Ingrese ID de la mascota a consultar: "))
                read_mascota_by_id(id_mascota)
            except ValueError:
                print("Error: El ID debe ser un número entero.")
            input("\nPresione ENTER para continuar...")
            
        elif opcion == "4":
            clear_screen()
            print("4. Modificar mascota")
            try:
                id_mascota = int(input("Ingrese ID de la mascota a modificar: "))
                print("[Sólo ingrese los datos a modificar, deje vacío si no quiere cambiar el campo]")
                nombre = input("Nuevo nombre (opcional): ")
                especie = input("Nueva especie (GATO/PERRO/AVE) (opcional): ")
                dueno = input("Nuevo dueño (opcional): ")
                fecha_nacimiento = input("Nueva fecha de nacimiento (DD-MM-YYYY) (opcional): ")

                nombre = nombre if nombre.strip() else None
                especie = especie if especie.strip() else None
                dueno = dueno if dueno.strip() else None
                fecha_nacimiento = fecha_nacimiento if fecha_nacimiento.strip() else None
                
                update_mascota(id_mascota, nombre, especie, dueno, fecha_nacimiento)
            except ValueError:
                print("Error: El ID debe ser un número entero.")
            input("\nPresione ENTER para continuar...")
        
        elif opcion == "5":
            clear_screen()
            print("5. Eliminar mascota")
            try:
                id_mascota = int(input("Ingrese ID de la mascota a eliminar: "))
                delete_mascota(id_mascota)
            except ValueError:
                print("Error: El ID debe ser un número entero.")
            input("\nPresione ENTER para continuar...")

        elif opcion == "6":
            clear_screen()
            print("6. Consultar detalles específicos (PERRO, GATO, AVE)")
            try:
                id_mascota = int(input("Ingrese ID de la mascota para ver detalles: "))
                read_mascota_by_id(id_mascota) # Muestra la info general primero
                read_perro_by_id(id_mascota)
                read_gato_by_id(id_mascota)
                read_ave_by_id(id_mascota)
            except ValueError:
                print("Error: El ID debe ser un número entero.")
            input("\nPresione ENTER para continuar...")

        elif opcion == "0":
            clear_screen()
            print("Volviendo al menú principal...")
            break
        else:
            clear_screen()
            print("Opción incorrecta, intente nuevamente.")
            input("Presione ENTER para continuar...")


def main():
    """Menú principal de la aplicación."""
    while True:
        clear_screen()
        print(
            """
                ====================================
                |     CRUD: Mascotas (Oracle)      |
                |----------------------------------|
                | 1. Crear todas las tablas        |
                | 2. Gestionar Mascotas (CRUD)     |
                | 0. Salir del sistema             |
                |----------------------------------|
                | * Las tablas Gato, Perro y Ave   |
                |   se manejan desde el menú 2.    |
                ====================================
            """
        )
        opcion = input("Elige una opción [1-2, 0]: ")

        if opcion == "1":
            clear_screen()
            create_all_tables()
            input("Presione ENTER para continuar...")
        elif opcion == "2":
            menu_mascotas()
        elif opcion == "0":
            clear_screen()
            print("Saliendo del sistema...")
            break
        else:
            clear_screen()
            print("Opción incorrecta, intente nuevamente.")
            input("Presione ENTER para continuar...")


if __name__ == "__main__":
    main()